### ISSUE TITLE
Could not find database with ID

### ISSUE THREAD

**Issue by liuxianyi** [zxjlm/NoteTrail#2]
notion_client.errors.APIResponseError: Could not find database with ID: 5dfca790-3787-4290-b22d-ec916bdc9f07. Make sure the relevant pages and databases are shared with your integration.

what is the database ID?

**Comment by zxjlm** [comment]
You can find the database id in the url link. For example, https://www.notion.so/<your_name>/<database_id> .  

To share database with your integration, the following steps may help you.  
1. You should register a bot via [notion developers page](https://developers.notion.com/)
2. Add connection to the page 
    ![](https://raw.githubusercontent.com/zxjlm/my-static-files/main/img/20221108174742.png)
